name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore ./PopulationReport.sln  # Correct path to the solution file

    - name: Build the project
      run: dotnet build ./PopulationReport.sln --configuration Release  # Correct path to the solution file

    - name: Run tests
      run: dotnet test ./PopulationReport.sln --configuration Release  # Correct path to the solution file

    - name: Publish the application
      run: dotnet publish ./PopulationReport.sln --configuration Release --output ./output  # Correct path to the solution file
