name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore ./My-Project/PopulationReport.sln  # Specify path to solution file

    - name: Build project
      run: dotnet build ./My-Project/PopulationReport.sln --configuration Release  # Specify path to solution file

    - name: Run tests
      run: dotnet test ./My-Project/PopulationReport.sln --configuration Release  # Specify path to solution file

    - name: Publish the application
      run: dotnet publish ./My-Project/PopulationReport.sln --configuration Release --output ./output  # Specify path to solution file
